const List<String> especialidadmusica = [
"Arpa P.M.A.E.",
"Bailaor Acompañante De Guitarra Flamenca",
"Canto P.M.A.E.",
"Caracterización P.M.A.E.",
"Clarinete P.M.A.E.",
"Clave P.M.A.E.",
"Clavecinista Acompañante",
"Contrabajo P.M.A.E.",
"Coro P.M.A.E.",
"Danza Aplicada al Arte Dramático P.M.A.E",
"Danza Clásica P.M.A.E.",
"Danza Contemporánea P.M.A.E.",
"Danza Española P.M.A.E.",
"Diccion y Expresion Oral P.M.A.E.",
"Dramaturgia y Escritura Dramatica. P.M.A.E.",
"Esgrima Aplic. al Arte Dramático P.M.A.E",
"Estética e Historia del Arte P.M.A.E.",
"Expresión Corporal P.M.A.E.",
"Fagot P.M.A.E.",
"Flamenco P.M.A.E.",
"Flauta de Pico P.M.A.E.",
"Flauta Travesera P.M.A.E.",
"Fundamentos de Composicion P.M.A.E.",
"Guitarra Flamenca P.M.A.E.",
"Guitarra P.M.A.E.",
"Guitarrista Acompañante Flamenco",
"Historia de la Musica P.M.A.E.",
"Idioma Aplicado al Canto P.M.A.E.",
"Indumentaria P.M.A.E.",
"Interpret. en el Teat del Texto P.M.A.E.",
"Lenguaje Musical P.M.A.E.",
"Oboe P.M.A.E.",
"Orquesta P.M.A.E.",
"Percusion P.M.A.E.",
"Pianista Acomp (Danza) En Cons. Superior",
"Pianista Acompañante (Canto)",
"Pianista Acompañante (Danza)",
"Pianista Acompañante (E.S.A.D.)",
"Pianista Acompañante (Instrumentos)",
"Piano P.M.A.E.",
"Saxofon P.M.A.E.",
"Tecnicas Escenicas P.M.A.E.",
"Trombon P.M.A.E.",
"Trompa P.M.A.E",
"Trompeta P.M.A.E.",
"Tuba P.M.A.E.",
"Viola P.M.A.E.",
"Violin P.M.A.E.",
"Violoncello P.M.A.E.",
""];