const List<String> especialidadsecundaria = [
  "Administracion de Empresas P.E.S.", 
"Administracion Empresas (Ingles)",
"Admon. de Empresas P.E.S. (Fp Distancia)",
"Aleman P.E.S.",
"Analisis y Quimica Industrial P.E.S.",
"Analisis y Quimica Ind. (Ingles) P.E.S.",
"Apoyo al Area Cientifica o Tecnologia",
"Apoyo al Area De Lengua y C. Sociales",
"Arabe",
"Asesoria y Proc. Imagen Personal P.E.S.",
"As. y Proc. Imagen Pers. (Ingles) P.E.S",
"Biologia y Geologia P.E.S.",
"Biologia y Geologia (Ingles) P.E.S.",
"Biologia y Geologia (Frances) P.E.S.",
"Biologia y Geologia (Aleman) P.E.S.",
"Biologia y Geologia P.E.S. (Ens. Distancia)",
"Construc. Civiles Y Edificacion P.E.S",
"Const. Civiles Y Edif. P.E.S. (F.P. Dual)",
"Cultura Clasica P.E.S.",
"Dibujo P.E.S.",
"Dibujo (Ingles) P.E.S.",
"Dibujo (Frances) P.E.S.",
"Dibujo (Ens. Distancia)", 
"Economia P.E.S.",
"Economia (Ingles) P.E.S.",
"Economia P.E.S. (Ens. Distancia)",
"Educacion Fisica P.E.S.",
"Educacion Fisica (Ingles) P.E.S.",
"Educacion Fisica P.E.S. C. Nueva Implantac.",
"Educacion Fisica P.E.S. (F.P.Dual)",
"Educ. Fisica P.E.S. (Nueva Implantacion)",
"Ed. Fisica Ens. Deport. R. Espec. (Dist)",
"Equipos Electronicos P.T.F.P.",
"Equipos Electronicos (Fp Dual)",
"Filosofia P.E.S.",
"Filosofia (Ingles) P.E.S.",
"Filosofia (Frances) P.E.S.",
"Filosofia P.E.S. (Ens. Distancia)",
"Fisica y Quimica P.E.S.",
"Fisica y Quimica (Ingles) P.E.S.",
"Fisica y Quimica (Frances) P.E.S.",
"Fisica y Quimica Pes (Ens. Distancia)",
"Formacion y Orientacion Laboral P.E.S.",
"Form.y Orientacion Laboral(Ingles) P.E.S",
"Form. Orient. Laboral P.E.S. (Fp Distancia)",
"Frances P.E.S.",
"Frances P.E.S. (Ens. Distancia)",
"Geografia E Historia P.E.S.",
"Geografia E Historia (Ingles) P.E.S.",
"Geografia E Historia (Frances) P.E.S.",
"Geografia E Historia (Aleman) P.E.S.",
"Geografia E Histor. P.E.S. (Ens. Distancia)",
"Hosteleria y Turismo P.E.S.",
"Hosteleria y Turismo (Ingles) P.E.S.",
"Hosteleria y Turismo P.E.S. (Fp Dual)",
"Hosteleria y Turismo P.E.S. (Semip)",
"Informatica P.E.S.",
"Informatica (Ingles) P.E.S.",
"Informatica P.E.S. (Fp Dual)",
"Informatica P.E.S. (Fp Distancia)",
"Informatica P.E.S. (Ens. Semipres.)",
"Ingles P.E.S.",
"Ingles P.E.S. (Bach.Bac.)",
"Ingles P.E.S. (Ens. Distancia)",
"Ingles P.E.S. (Portugues 2ªlengua)",
"Inst.Mtto.Equipos Term.Fuidos P.T.F.P.",
"Inst. y Mtto. Eq. Term. Fluidos (Dual)",
"Instalaciones Electrotecnicas P.T.F.P.",
"Instalaciones Electrotecnicas (Fp Dual)",
"Intervencion Sociocomunitaria P.E.S.",
"Intervencion Sociocomunitaria (Ingles)",
"Interv. Sociocom. P.E.S. (Fp Dual)",
"Interv. Sociocomunit. P.E.S. (Fp Distancia)",
"Interv. Sociocom. P.E.S. C. Nueva Implantac",
"Italiano P.E.S.",
"Lengua Castellana y Literatura P.E.S.",
"Leng. Cast. y Literat. (Ens. Distancia)",
"Lengua Castellana y Literatura Pes (Bae)",
"Lenguaje de Signos (Bolsa)",
"Lenguaje de Signos (C. Compartido)",
"Maquinas, Servicios y Produccion P.T.F.P",
"Matematicas P.E.S.",
"Matematicas (Ingles) P.E.S.",
"Matematicas (Frances) P.E.S.",
"Matematicas (Aleman) P.E.S.",
"Matematicas P.E.S. (Ens. Distancia)",
"Musica P.E.S.",
"Musica (Ingles) P.E.S.",
"Musica (Frances) P.E.S.",
"Navegacion e Instalaciones Marinas P.E.S",
"Oficina de Proyec. Construccion",
"Operac. y Equ. Elab. Prod. Alimentos",
"Operac. y Equipos Prod. Agraria",
"Operac. y Equip. Prod. Agraria (Fp Dual)",
"Operaciones y Equip. Prod. Agr.(Ptval)",
"Operaciones de Procesos",
"Operaciones de Procesos (Fp Dual)",
"Organizacion y Gestion Comercial P.E.S.",
"Org.y Gestion Comercial (Frances) P.E.S.",
"Org. Gest. Comercial P.E.S. (Fp Distancia)",
"Org. y Gestion Comercial P.E.S. (Fp Dual)",
"Org. y Procesos Manten. Vehiculos P.E.S.",
"Org. y Proc. Mant. Veh. P.E.S. (Fp Dual)",
"Org. y Proy. Fabricacion Mecanica P.E.S.",
"Org.y Proy Fabric. Mec. P.E.S. (Fp Dual)",
"Orientacion Educativa P.E.S.",
"Orient. Educativa P.E.S. (Salud Mental)",
"Orientacion Educativa P.E.S. (P.Acomp)",
"Proc. Diag. Clin. y Prod. Ortopr. P.E.S.",
"P.Diag.Clin. y Prod.Otpr. (Ingles) P.E.S.",
"Pes Mixto Ingles/Aleman",
"Pes Ingles - Frances",
"Pes Mixto Italiano/Frances",
"Proc .Cultiv. Acuicola (P. Especif.)",
"Proc. Gestion Administrativa",
"Proc. Gestion Administrativa (Ingles)",
"Proc. Gestion Administrativa (Fp Dual)",
"Proc. Gestion Administrativa (Fp Semi)",
"Proc. Gestion Administrativa (Fp Dist.)",
"Proc. Indust. Alimentaria (Cfgs)",
"Proc. Industria Alim. P.E.S. (Fp Dual)",
"Proc. Sanitarios y Asistenciales",
"Proc. Sanitarios Asistenc. (Fp Dual)",
"Proc.San.y Asistenc. (Higiene Bucodent)",
"Procesos y Medios De Comunicacion P.E.S.",
"Proc. y Medios de Comunicacion (Ingles)",
"Proc. y Prod. en Madera y Mueble P.E.S.",
"Proc. y Prod. Textil, Conf. Piel P.E.S.",
"Procesos Comerciales",
"Procesos Comerciales (Ptval)",
"Procesos De Produccion Agraria P.E.S.",
"Procesos De Produccion Agraria (Fp Dual)",
"Procesos Industria Alimentaria P.E.S.",
"Procesos Industria Alimentaria (Ingles)",
"Procesos Sanitarios P.E.S.",
"Procesos Sanitarios P.E.S. (Fp Dual)",
"Procesos Sanitarios P.E.S.(Ingles)",
"Proc. y Prod. En Artes Graficas P.E.S.",
"Prog. Espec. de Fpb Serv.Administrativos",
"Prog. Espec. Fpb Informatica y Comunicac",
"Prog. Espec. Fpb Act. Domest. Limp. Edif",
"Prog. Espec. Fpb Informatica Oficina",
"Servicios a la Comunidad",
"Servicios a la Comunidad (Ingles)",
"Servicios a la Comunidad (Dual Ingles)",
"Servicios a la Comunidad (Fp Dual)",
"Servicios a la Comunidad (Ptval)",
"Sist. Electrotecnicos y Autom. P.E.S.",
"Sistemas Electronicos P.E.S.",
"Sistemas y Aplic. Informaticos",
"Sistemas y Aplic. Informaticos (Ingles)",
"Sist. y Aplicac. Informaticas (Fp Dual)",
"Sist. y Aplic. Informaticas (Fp Distan.)",
"Sistemas y Aplic. Informaticos (Fp Semi)",
"Tec. y Proc. de Imagen y Sonido",
"Tecnologia P.E.S.",
"Tecnologia (Ingles) P.E.S.",
"Tecnologia (Frances) P.E.S.",
""];
