const List<String> especialidadfp = [
"Cocina y Pastelería",
"Cocina y Pastelería (Fp Dual)",
"Cocina y Pastelería (Ptval)",
"Prog. Espec. Fpb Cocina y Restauración",
"Prog. Espec. Fpb Aloj. y Lavandería",
"Prog. Espec. Fpb Act. Domest. Limpieza. Edif",
"Equipos Electronicos P.T.F.P.",
"Estética",
"Fabric. e Inst. Carpint. Mueble",
"Fabric. e Inst. Carpint. Mueble. (Fp Dual)",
"Fabric. e Inst. Carpint. Mueble (Ptval)",
"Prog. Esp. Fpb Carpintería y Mueble",		
"Inst. Mtto. Equipos Term.Fuidos P.T.F.P.",
"Inst. y Mtto. Eq. Term. Fluidos (Dual)",
"Instalaciones Electrotecnicas P.T.F.P.",
"Instalaciones Electrotécnicas (Fp Dual)",
"Laboratorio P.T.F.P.",
"Mantenimiento de Vehículos",
"Mantenimiento de Vehículos (Fp Dual)",
"Mecanizado y Mto. De Máquinas",
"Oficina de Proyec. Construccion P.T.F.P.",
"Org. y Proy. Fabricacion Mecanica P.E.S.",
"Or. Proy. Fabric. Mec. Pes(Bil.Ing-F.Cat",
"Org. y Pr. F. Mec. P.E.S. (Bil. I Fp Du)",
"Operaciones de Procesos P.T.F.P.",
"Operac. y Equipos. Prod. Agraria (Fp Dual)",
"Operac. y Equipos Prod. Agraria P.T.F.P.",
"Operaciones y Equip. Prod. Agr.(Ptval)",
"Prog. Espec. de Fpb Agroj. y Comp. Flor",
"Patronaje y Confección P.T.F.P.",
"Peluquería",
"P. Diag. Clin. Ortopro. (Ingles) P.T.F.P.",
"Proc. Diag. Clin. y Ortoprotesic. P.T.F.P.",
"Proc. Sanit. Asist. Ptfp (Fp Dual)",
"Proc. Sanitarios y Asistenciales P.T.F.P.",
"Procesos Comerciales (Ingles) P.T.F.P.",
"Procesos Comerciales (Ptval)",
"Procesos Comerciales P.T.F.P.",
"Prog. Espec. Fpb Servicios Comerciales",
"Proc. Gest. Adva. Ftfp (Fp Distancia)",
"Proc. Gestion Administrativa P.T.F.P.",
"Proc. Gestión Admin. P.T.F.P. (Fp Dual)",
"Prog. Espec. de Fpb Serv.Administrativos",
"Prog. Espec. Fpb Act. Domest. Limpieza. Edif",
"Prog.Espec. Fpb Aloj. Y Lavandería",
"Pr. Espec. Fpb Agrojardín. Compos. Floral.",
"Prog. Espec. Fpb Cocina Y Restauración",
"Prog. Espec. Fpb Servicios Comerciales",
"Prog. Esp. Fpb Carpintería Y Mueble",
"Producción en Artes Gráficas",
"Servicios a la Comunidad (Fp Distancia)",
"Servicios a la Comunidad P.T.F.P.",
"Servicios a la Comunidad Ptfp (Fp Dual)",
"Servicios de Restauración (Ptval)",
"Servicios de Restauración P.T.F.P.",
"Servicios Restauración (Ingles) P.T.F.P",
"Sist. y Apl. Infor. P.T.F.P. (En. Semip)",
"Sist. y Aplic. Inform P.T.F.P. (Fp Dual)",
"Sistemas y Aplic. Informaticos P.T.F.P.",
"Prog. Espec. Fpb Informática Oficina",
"Prog. Espec. Fpb Informática Y Comunicac",
"Soldadura",
"Soldadura (Fp Dual)",
"Servicios de Restauración",
"Servicios de Restauración (Inglés)",
"Taller de Vidrio y Cerámica (Ptval)",
"Tec y Pr de Im Y Sonido (Cfgs Sonido)",
"Tec. y Proc. De Imagen Ptfp(Cfgs Sonido)",
"Tec. y Proc. De Imagen y Sonido (Ingles)",	
"Tec. y Proc. De Imagen y Sonido P.T.F.P.",
""];
