const List<String> especialidadeoi = [
"Aleman P.E.O.I.",
"Aleman P.E.O.I. (Ens. Distancia)",
"Arabe P.E.O.I.",
"Espanol / Inglés P.E.O.I.",
"Espanol P.E.O.I.",
"Frances P.E.O.I.",
"Frances P.E.O.I. (Ens. Distancia)",
"Francés - Italiano Bilingüe. P.E.O.I.",
"Inglés P.E.O.I.",
"Inglés P.E.O.I. (Ens. Distancia)",
"Inglés - Alemán Biling. P.E.O.I.",
"Inglés - Arabe Peoi (Bilingüe)",
"Inglés - Francés Bilingüe. P.E.O.I.",
"Inglés - Italiano Bilingüe. P.E.O.I.",
"Inglés - Portugues Bilingüe P.E.O.I.",
"Italiano P.E.O.I.",
"Japonés P.E.O.I.",
""];