const List<String> especialidadarte = [
"Medios Audiovisuales",
"Medios Informáticos",
"Cerámica",
"Diseño de Moda",
"Diseño de Producto",
"Diseño Grafico",
"Dibujo Artistico y Color",
"Dibujo Técnico",
"Diseno de Interiores",
"Fotografía",
"Historia del Arte",
"Materiales y Tecnol.: Diseño",
"Organización Industrial y Legislación",
"Volumen",
""];
