const List<String> especialidadmaestros = [
"Apoyo Compensacion",
"Ciencias Sociales-Geografía E Historia",
"Educ. Fisica (Primaria)- Bilingüe Inglés",
"Educ. Fisica (Primaria)-Bilingüe Alemán",
"Educ. Fisica (Primaria)-Bilingüe Francés",
"Educación Física",
"Educación Física (Secundaria)",
"Educación Infantil",
"Educacion Infantil - Bilingue Ingles",
"Educación Primaria", 
"Educación Primaria-Bilingüe Alemán",
"Educacion Primaria-Bilingue Ingles",
"Educacion Primaria-Bilingue Frances",
"Idioma Extranjero-Francés (Secundaria)",
"Idioma Extranjero-Inglés (Secundaria)",
"Lengua Castellana",
"Lengua Extranjera-Alemán",
"Lengua Extranjera-Francés",
"Lengua Extranjera-Inglés",
"Maestros De E.O.E.",
"Maestros En Fpb De Alumnado De N.E.E.",
"Matemáticas",
"Música",
"Música (Secundaria)",
"Música (Primaria)-Bilingüe Francés",
"Música (Primaria)-Bilingüe Inglés",
"Pedagogia Terapeutica",
"Pedagogia Terapeutica (Transformate)",
"Pedagogía Terapéutica Eso",
"Pedagogía Terapéutica Eso (Transformate)",
"Programa Transición Vida Adulta y Laboral",
""];
