// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG6ESA9TEKJpt1wiwOtnG1GiGKGm-AdS0',
    appId: '1:895267019802:android:4362e97eb84770fcc6c5a3',
    messagingSenderId: '895267019802',
    projectId: 'flutter-vacantes',
    storageBucket: 'flutter-vacantes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-yOlfqHZId1KQY4B9aQboXX3pvuVlfBk',
    appId: '1:895267019802:ios:642172402ac5fba9c6c5a3',
    messagingSenderId: '895267019802',
    projectId: 'flutter-vacantes',
    storageBucket: 'flutter-vacantes.appspot.com',
    iosClientId: '895267019802-gp7k8fe3olnfkiusi846p4k41ngp9pq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.appVacantes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb9GQv1xWnh_VQznX2_IgVBK5tDBC0NyQ',
    appId: '1:895267019802:web:c3eeeba907de7ac0c6c5a3',
    messagingSenderId: '895267019802',
    projectId: 'flutter-vacantes',
    authDomain: 'flutter-vacantes.firebaseapp.com',
    storageBucket: 'flutter-vacantes.appspot.com',
    measurementId: 'G-QS8D32PXYY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-yOlfqHZId1KQY4B9aQboXX3pvuVlfBk',
    appId: '1:895267019802:ios:642172402ac5fba9c6c5a3',
    messagingSenderId: '895267019802',
    projectId: 'flutter-vacantes',
    storageBucket: 'flutter-vacantes.appspot.com',
    iosClientId: '895267019802-gp7k8fe3olnfkiusi846p4k41ngp9pq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.appVacantes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb9GQv1xWnh_VQznX2_IgVBK5tDBC0NyQ',
    appId: '1:895267019802:web:78ec24f0858ef392c6c5a3',
    messagingSenderId: '895267019802',
    projectId: 'flutter-vacantes',
    authDomain: 'flutter-vacantes.firebaseapp.com',
    storageBucket: 'flutter-vacantes.appspot.com',
    measurementId: 'G-T10PWTFBBF',
  );

}